### ISSUE TITLE
Default Armature Pose Settings

### ISSUE THREAD

**Issue by franklinblanco** [kaosat-dev/Blenvy#131]
Hi, changing the pose of my armature I realized the gltf_auto_export plugin doesn't persist these changes in the .glb file.
In blender:
![Screenshot 2024-02-17 at 5 52 41 PM](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/72827992/8a127e95-dc6a-42ea-a1b2-33d14f82ba43)

In bevy:
![Screenshot 2024-02-17 at 5 54 05 PM](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/72827992/c41906b1-015d-407f-b668-f6be69f59744)

In the normal export gltf 2.0 export panel there's a dedicated Armature menu and there you can choose to use the rest position Armature.

![Screenshot 2024-02-17 at 5 55 51 PM](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/72827992/af22a4ac-cb30-4565-92c7-b01eb3692af1)

Is there any way to get around this with the current version of the plugin?

Once again, thanks for your time and work into this. This plugin is the reason I took the leap to choose bevy as my game engine of choice!

**Comment by kaosat-dev** [comment]
Hi @franklinblanco ! 
Thanks for the kind words :)
Unfortunately it is not possible right now , as the UI of the normal gltf export panel is sadly **not** reusable , so I had to recreate as much as I could, manually, but it was too complex to add all the options, sorry :(
**However** since I explored this a bit further recently, I will likely soon get rid of the "normal" gltf export settings in ```gltf_auto_export``` , and make it use the **stored** settings of the normal exporter.
I ie the future workflow would be
* set the standard gltf export options (will likely add a button to go to that in the auto export UI)
* click on "remember export settings"
* setup auto_export, that will use the settings above

**Comment by franklinblanco** [comment]
Alrighty, no problem then! I'll close this then. Have a great rest of your day!

**Comment by kaosat-dev** [comment]
@franklinblanco Sorry, I might not have been clear in my wording, but this is not yet done, and is a real issue, so I will re-open until it is solved if you don't mind ?

**Comment by franklinblanco** [comment]
Yeah, sounds good. Sometimes devs don't like having open issues sitting there, that's why i closed it. But yeah, go ahead
