### ISSUE TITLE
Problems with bounding boxes and animation mixing

### ISSUE THREAD

**Issue by DylanRJohnston** [kaosat-dev/Blenvy#179]
I've been encountering a weird issue where at certain camera angles portions of the mesh of a blueprinted entity are culled.

![Apr-10-2024 19-19-43](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/5708800/fa5b5235-c33b-4c2d-bd79-547205e56d51)

Enabling AABB gizmos shows a bunch of bounding boxes floating off in space. 

![Screenshot 2024-04-11 at 10 42 51 am](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/5708800/07d4e80a-30d0-4eea-bd63-15613c61be2c)

Inspecting the original model, and the one exported from blender show large differences in their reported bounding boxes and the animations from the different models are getting all mixed in together.

![Screenshot 2024-04-11 at 10 36 13 am](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/5708800/282bc6ca-30db-457d-9d87-37fe571321bc)

![Screenshot 2024-04-11 at 10 37 47 am](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/5708800/a4be225a-e961-45b8-b084-b0c820a8d573)

Perhaps I'm doing something catastrophically incorrect with the way I've setup my blender project but I've followed the video guides closely and can't figure out what I'm doing incorrectly.

**Comment by DylanRJohnston** [comment]
Copying the original glb file over the exported one in the `library` folder results in the correctly placed bounding boxes. 

![Screenshot 2024-04-11 at 11 33 11 am](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/5708800/0f77f53a-9c07-4022-ad61-846c1322f777)

**Comment by DylanRJohnston** [comment]
This seems to be a related issue experienced by the three.js community https://github.com/mrdoob/three.js/issues/14499

**Comment by kaosat-dev** [comment]
Hi @DylanRJohnston !
If I understand correctly : 
* the issue with bounding boxes is fixed by the fix in the thread on the Bevy github you linked to ?
* the issue with animations is they get attached to the wrong model/blueprint or do all models have all animations from all other models ?

There is a HUGE pr that I hope to release this week that fixes a ton of issues with animations & changes the way animations are "attached" to blueprints, so I hope that will fix this issue as well.
The PR on the Blender side is not quite consumption ready , but I'll ping you once it is.
