### ISSUE TITLE
Custom Properties are only imported from objects

### ISSUE THREAD

**Issue by spooky-th-ghost** [kaosat-dev/Blenvy#4]
Don't know if this is out of scope for this project, but while integrating i've found that Custom Properties are only imported on an object level, it doesn't appear it's possible to have a struct be placed directly on the entity that contains the `Mesh` component when loading a GLTF scene

**Comment by GitGhillie** [comment]
I haven't run into this myself, but maybe it's related to https://github.com/bevyengine/bevy/issues/4823?

**Comment by kaosat-dev** [comment]
Sorry it took me so long to answer: 
I think the problem is double:
* the custom properties are only exported at Object level from Blender (this I know for sure)
* I think the Bevy issue linked by @GitGhillie would also prevent it from working on the Bevy side.

**Comment by kaosat-dev** [comment]
@spooky-th-ghost & @GitGhillie , this might be an older issue, but I realized recently that what I said back then is totally false!
* Blender does export custom properties in gltf files at various levels (scenes, materials). I could have sworn this was not the case in older versions, but I stand corrected
* It would really solve issues if we could support components on any entity ( it would also reduce some of the workaround done in the code in this repo)
* the issue comes 100% from the issue @GitGhillie mentioned: depending on the feedback there, I will likely submit a PR at Bevy level.
* I can also confirm that

**Comment by kaosat-dev** [comment]
Pr for Bevy is out https://github.com/bevyengine/bevy/pull/13453

**Comment by GitGhillie** [comment]
Awesome, that will make it 100x easier to explain to people how to convert meshes to colliders when using rapier/xpbd
